version: "3.8"

services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - dragonfly_data:/data
    environment:
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["--dir=/data", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  dragonfly_data:
    driver: local
